// Tenants actions
export const UPDATE_TENANTS = "UPDATE_TENANTS";
export const ADD_TENANT = "ADD_TENANT";
export const SET_ACTIVE_TENANT = "SET_ACTIVE_TENANT";

// Customer actions
export const UPDATE_CUSTOMERS = "UPDATE_CUSTOMERS";

// Product actions
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCTS_SEARCH_HISTORY = "UPDATE_PRODUCTS_SEARCH_HISTORY";
export const UPDATE_ACTIVE_PRODUCT = "UPDATE_ACTIVE_PRODUCT";
export const UPDATE_SUCCESS_MESSAGE = "UPDATE_SUCCESS_MESSAGE";
export const UPDATE_ERROR_MESSAGE = "UPDATE_ERROR_MESSAGE";